export type QuestionType = "mcq" | "true_false";

export interface CERQuestion {
  id: string;
  type: QuestionType;
  domain: string;
  chapter: number;
  question: string;
  options: { a: string; b: string; c?: string; d?: string };
  correct: "a" | "b" | "c" | "d";
  explanation: string;
  difficulty: "easy" | "medium" | "hard";
}

export const cerQuestions: CERQuestion[] = [

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 1: Introduction to Endoscopes
  // ═══════════════════════════════════════════════════════════════

  {
    id: "cer-ch1-1",
    type: "mcq",
    domain: "Endoscope Overview & Anatomy",
    chapter: 1,
    question: "Which of the following is NOT one of the three primary ways endoscopes are used to meet patient needs?",
    options: { a: "Routine screening", b: "Diagnostic treatment", c: "Cosmetic enhancement", d: "Therapeutic treatment" },
    correct: "c",
    explanation: "Endoscopes are used for routine screening, diagnostic treatment, and therapeutic treatment. Cosmetic enhancement is not a recognized clinical application of endoscopy.",
    difficulty: "easy",
  },
  {
    id: "cer-ch1-2",
    type: "mcq",
    domain: "Endoscope Overview & Anatomy",
    chapter: 1,
    question: "Which of the following best describes a key challenge endoscope reprocessing professionals face?",
    options: { a: "Endoscopes are too lightweight", b: "Pressure to turn over equipment quickly", c: "No training programs exist", d: "Endoscopes never require reprocessing" },
    correct: "b",
    explanation: "Two documented challenges are processing each endoscope correctly with precision and care, and pressure to turn over equipment quickly. Time pressure is a major human factors concern in reprocessing.",
    difficulty: "easy",
  },
  {
    id: "cer-ch1-3",
    type: "true_false",
    domain: "Endoscope Overview & Anatomy",
    chapter: 1,
    question: "Understanding the risks of improper endoscope processing — including cross-contamination, infection, and death — is a core competency for reprocessing technicians.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. Technicians must understand these risks to approach their work with the appropriate level of care and precision. This knowledge is foundational to patient safety in endoscopy.",
    difficulty: "easy",
  },
  {
    id: "cer-ch1-4",
    type: "true_false",
    domain: "Endoscope Overview & Anatomy",
    chapter: 1,
    question: "An endoscope reprocessing technician only needs to understand the manual cleaning process — other steps such as leak testing and HLD are handled by nursing staff.",
    options: { a: "True", b: "False" },
    correct: "b",
    explanation: "False. Endoscope reprocessing technicians are responsible for the entire reprocessing workflow including point-of-use handling, leak testing, manual cleaning, HLD/sterilization, inspection, and storage.",
    difficulty: "easy",
  },
  {
    id: "cer-ch1-5",
    type: "mcq",
    domain: "Endoscope Overview & Anatomy",
    chapter: 1,
    question: "Which of the following is an important competency for endoscope reprocessing technicians related to microbiology?",
    options: { a: "Prescribing antibiotics", b: "Understanding the importance of preventing biofilm growth on medical devices", c: "Diagnosing patient infections", d: "Performing blood cultures" },
    correct: "b",
    explanation: "Understanding biofilm formation and prevention is a critical competency. Biofilm is a major driver of healthcare-associated infections related to endoscopes and is resistant to standard cleaning if allowed to form.",
    difficulty: "medium",
  },
  {
    id: "cer-ch1-6",
    type: "true_false",
    domain: "Endoscope Overview & Anatomy",
    chapter: 1,
    question: "Lack of inventory is one of the documented challenges endoscope reprocessing professionals face.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. Lack of inventory is listed alongside processing each scope correctly with precision and care, and pressure to turn over equipment quickly, as a documented challenge in endoscope reprocessing.",
    difficulty: "medium",
  },
  {
    id: "cer-ch1-7",
    type: "mcq",
    domain: "Endoscope Overview & Anatomy",
    chapter: 1,
    question: "Which reprocessing knowledge area involves understanding what to do when an endoscope fails a leak test?",
    options: { a: "Sterilization process documentation", b: "Proper leak testing procedures and failure protocols", c: "Insurance billing compliance", d: "Patient scheduling" },
    correct: "b",
    explanation: "Technicians must understand how to properly perform leak testing AND know the steps to take when an endoscope fails. Failing to follow correct failure protocols can result in damaged scopes entering patient use.",
    difficulty: "medium",
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 2: Overview of Flexible Endoscopes
  // ═══════════════════════════════════════════════════════════════

  {
    id: "cer-ch2-1",
    type: "mcq",
    domain: "Endoscope Overview & Anatomy",
    chapter: 2,
    question: "How many general components are common to most flexible endoscopes?",
    options: { a: "Four", b: "Five", c: "Six", d: "Eight" },
    correct: "c",
    explanation: "Most flexible endoscopes share six general components: (1) light guide tube, (2) universal cord, (3) control body, (4) internal instrument channels, (5) insertion tube, and (6) bending section/distal tip.",
    difficulty: "easy",
  },
  {
    id: "cer-ch2-2",
    type: "mcq",
    domain: "Endoscope Overview & Anatomy",
    chapter: 2,
    question: "Which component of a flexible endoscope contains the water/suction valves and angulation knobs?",
    options: { a: "Insertion tube", b: "Universal cord", c: "Bending section", d: "Control body" },
    correct: "d",
    explanation: "The control body contains the water/suction valves and angulation knobs used by the physician during the procedure. It connects the insertion tube to the universal cord.",
    difficulty: "medium",
  },
  {
    id: "cer-ch2-3",
    type: "mcq",
    domain: "Endoscope Overview & Anatomy",
    chapter: 2,
    question: "Which endoscope is used to diagnose inflammatory bowel disease?",
    options: { a: "Gastroscope", b: "Colonoscope", c: "Bronchoscope", d: "Cystoscope" },
    correct: "b",
    explanation: "A colonoscope examines the lower gastrointestinal tract (colon) and is used to diagnose conditions such as inflammatory bowel disease, polyps, and colorectal cancer.",
    difficulty: "easy",
  },
  {
    id: "cer-ch2-4",
    type: "mcq",
    domain: "Endoscope Overview & Anatomy",
    chapter: 2,
    question: "Which endoscope is specifically used to remove gallstones?",
    options: { a: "Cystoscope", b: "Enteroscope", c: "Choledochoscope", d: "Ureteroscope" },
    correct: "c",
    explanation: "The choledochoscope is used to visualize and remove gallstones from the bile ducts. It should not be confused with the cystoscope (bladder) or ureteroscope (ureters/kidney stones).",
    difficulty: "medium",
  },
  {
    id: "cer-ch2-5",
    type: "mcq",
    domain: "Endoscope Overview & Anatomy",
    chapter: 2,
    question: "Which endoscope examines the upper airway and nasal passages?",
    options: { a: "Bronchoscope", b: "Gastroscope", c: "Rhinolaryngoscope", d: "Enteroscope" },
    correct: "c",
    explanation: "The rhinolaryngoscope examines the upper airway and nasal passages. The bronchoscope examines the throat, trachea, and lower airways — a distinct and deeper anatomical region.",
    difficulty: "easy",
  },
  {
    id: "cer-ch2-6",
    type: "true_false",
    domain: "Endoscope Overview & Anatomy",
    chapter: 2,
    question: "A ureteroscope visualizes the urinary tubes that connect the kidneys to the bladder.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. The ureteroscope is used to visualize the ureters — the urinary tubes connecting the kidneys to the bladder. It is commonly used to treat kidney and ureteral stones.",
    difficulty: "easy",
  },
  {
    id: "cer-ch2-7",
    type: "true_false",
    domain: "Endoscope Overview & Anatomy",
    chapter: 2,
    question: "A hysteroscope is used to examine the uterus.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. A hysteroscope is used to visualize the uterus. It can be used for both diagnostic and therapeutic purposes, such as removing fibroids or polyps.",
    difficulty: "easy",
  },
  {
    id: "cer-ch2-8",
    type: "mcq",
    domain: "Endoscope Overview & Anatomy",
    chapter: 2,
    question: "Which section of a flexible endoscope articulates to aid insertion into curved areas?",
    options: { a: "Universal cord", b: "Bending section", c: "Light guide tube", d: "Control body" },
    correct: "b",
    explanation: "The bending section (distal tip) articulates to allow navigation through curved anatomical passages. The physician controls the bend angle using the angulation knobs on the control body.",
    difficulty: "medium",
  },
  {
    id: "cer-ch2-9",
    type: "true_false",
    domain: "Endoscope Overview & Anatomy",
    chapter: 2,
    question: "Operative (therapeutic) flexible endoscopes are primarily used to identify possible disease.",
    options: { a: "True", b: "False" },
    correct: "b",
    explanation: "False. Operative (therapeutic) endoscopes are used to perform treatments, not primarily to identify disease. Diagnostic endoscopes identify disease. Therapeutic endoscopes treat it — for example by removing polyps or stones.",
    difficulty: "medium",
  },
  {
    id: "cer-ch2-10",
    type: "mcq",
    domain: "Endoscope Overview & Anatomy",
    chapter: 2,
    question: "Information for reprocessing specific endoscopes can most reliably be found in:",
    options: { a: "The hospital's general policy manual", b: "The endoscope manufacturer's Instructions for Use (IFU)", c: "Online nursing forums", d: "OSHA standards" },
    correct: "b",
    explanation: "The endoscope manufacturer's Instructions for Use (IFU) is the most reliable source for reprocessing information for a specific endoscope. IFUs are required by the FDA and are device-specific.",
    difficulty: "easy",
  },
  {
    id: "cer-ch2-11",
    type: "true_false",
    domain: "Endoscope Overview & Anatomy",
    chapter: 2,
    question: "An enteroscope is used to examine the small intestine.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. An enteroscope is specifically designed to examine the small intestine, which is beyond the reach of a standard gastroscope and colonoscope.",
    difficulty: "easy",
  },
  {
    id: "cer-ch2-12",
    type: "mcq",
    domain: "Endoscope Overview & Anatomy",
    chapter: 2,
    question: "The duodenoscope is unique among flexible endoscopes because it has:",
    options: { a: "A longer insertion tube than all other scopes", b: "A movable elevator mechanism that has been linked to infection outbreaks", c: "No working channel", d: "A rigid bending section" },
    correct: "b",
    explanation: "The duodenoscope has a movable elevator mechanism at its distal tip. This complex design creates hard-to-clean recesses that have been linked to healthcare-associated infection outbreaks, making it one of the highest-risk endoscopes to reprocess.",
    difficulty: "hard",
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 3: Microbiology Basics
  // ═══════════════════════════════════════════════════════════════

  {
    id: "cer-ch3-1",
    type: "mcq",
    domain: "Microbiology",
    chapter: 3,
    question: "How many primary stains are used for bacteria identification?",
    options: { a: "Two", b: "Three", c: "Four", d: "Five" },
    correct: "c",
    explanation: "The four primary stains used for bacteria identification are: Gram stain, Acid fast stain, Endospore stain, and Capsule stain. Each is used to identify different bacterial characteristics.",
    difficulty: "medium",
  },
  {
    id: "cer-ch3-2",
    type: "mcq",
    domain: "Microbiology",
    chapter: 3,
    question: "Which stain is specifically used to identify Mycobacterium tuberculosis?",
    options: { a: "Gram stain", b: "Capsule stain", c: "Endospore stain", d: "Acid fast stain" },
    correct: "d",
    explanation: "The acid fast stain is used specifically to identify Mycobacterium tuberculosis and other acid-fast organisms. These bacteria have a waxy cell wall that resists standard Gram staining.",
    difficulty: "medium",
  },
  {
    id: "cer-ch3-3",
    type: "mcq",
    domain: "Microbiology",
    chapter: 3,
    question: "Bacteria that stain purple in the Gram staining process are classified as:",
    options: { a: "Gram negative", b: "Gram positive", c: "Acid fast", d: "Endospore forming" },
    correct: "b",
    explanation: "Gram positive bacteria retain the crystal violet stain and appear purple. Gram negative bacteria lose the purple stain during decolorization and appear red/pink after counterstaining with safranin.",
    difficulty: "easy",
  },
  {
    id: "cer-ch3-4",
    type: "true_false",
    domain: "Microbiology",
    chapter: 3,
    question: "Symbiotic bacteria are harmful to humans.",
    options: { a: "True", b: "False" },
    correct: "b",
    explanation: "False. Symbiotic bacteria are beneficial to humans — they help humans in some way, such as gut flora that aid in digestion and immune function. Pathogenic bacteria are the ones that cause harm.",
    difficulty: "easy",
  },
  {
    id: "cer-ch3-5",
    type: "mcq",
    domain: "Microbiology",
    chapter: 3,
    question: "What is a biofilm?",
    options: { a: "A single-species colony in liquid suspension", b: "A collection of microorganisms that attach to surfaces and form a protective gel colony", c: "A type of disinfectant-resistant endospore", d: "A protein layer on metal surfaces only" },
    correct: "b",
    explanation: "A biofilm is a collection of microorganisms that attach to surfaces and each other, forming a colony that produces a protective gel. This gel matrix makes biofilms extremely difficult to penetrate with detergents and disinfectants.",
    difficulty: "medium",
  },
  {
    id: "cer-ch3-6",
    type: "true_false",
    domain: "Microbiology",
    chapter: 3,
    question: "An opportunistic infection is caused by a microorganism that usually does not cause disease.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. Opportunistic infections are caused by microorganisms that normally do not cause disease in healthy individuals but can cause serious infections in immunocompromised patients — such as those undergoing chemotherapy or with HIV.",
    difficulty: "medium",
  },
  {
    id: "cer-ch3-7",
    type: "mcq",
    domain: "Microbiology",
    chapter: 3,
    question: "How long has Pseudomonas aeruginosa been known to survive on a dry, non-living surface?",
    options: { a: "Up to 24 hours", b: "Up to 1 week", c: "Six hours to 16 months", d: "One to three months only" },
    correct: "c",
    explanation: "Pseudomonas aeruginosa can survive on dry surfaces for six hours to 16 months. This remarkable environmental survival ability makes contaminated endoscopes a serious infection risk if not properly reprocessed.",
    difficulty: "hard",
  },
  {
    id: "cer-ch3-8",
    type: "true_false",
    domain: "Microbiology",
    chapter: 3,
    question: "Viruses are larger than bacteria.",
    options: { a: "True", b: "False" },
    correct: "b",
    explanation: "False. Viruses are generally much smaller than bacteria. Bacteria are typically 1–10 micrometers in size, while viruses are typically 20–300 nanometers — roughly 10–100 times smaller.",
    difficulty: "easy",
  },
  {
    id: "cer-ch3-9",
    type: "true_false",
    domain: "Microbiology",
    chapter: 3,
    question: "Enveloped viruses are easier to disable than non-enveloped viruses.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. Enveloped viruses (like HIV and influenza) have a lipid outer membrane that is relatively easy to disrupt with disinfectants. Non-enveloped viruses lack this membrane and are generally more resistant to disinfection.",
    difficulty: "medium",
  },
  {
    id: "cer-ch3-10",
    type: "true_false",
    domain: "Microbiology",
    chapter: 3,
    question: "Biofilm is a colony of only one type of bacteria that joins together.",
    options: { a: "True", b: "False" },
    correct: "b",
    explanation: "False. Biofilm is typically a mixed community of multiple microorganism species — not a single type. This diversity makes biofilms more resilient and harder to eliminate than single-species colonies.",
    difficulty: "medium",
  },
  {
    id: "cer-ch3-11",
    type: "mcq",
    domain: "Microbiology",
    chapter: 3,
    question: "Bacteria spores are resistant to which of the following?",
    options: { a: "Radiation only", b: "Heat only", c: "Chemicals only", d: "Radiation, heat, and chemicals" },
    correct: "d",
    explanation: "Bacterial endospores are highly resistant to radiation, heat, and chemicals. This extraordinary resistance is why spore-forming bacteria such as Clostridioides difficile require sterilization, not just disinfection, to eliminate.",
    difficulty: "medium",
  },
  {
    id: "cer-ch3-12",
    type: "true_false",
    domain: "Microbiology",
    chapter: 3,
    question: "While bacteria can be pathogenic, fungus and parasites cannot be pathogenic.",
    options: { a: "True", b: "False" },
    correct: "b",
    explanation: "False. Fungi, parasites, bacteria, and viruses can all be pathogenic. Fungal infections (e.g., Candida) and parasitic infections (e.g., Giardia) are well-documented causes of healthcare-associated infections.",
    difficulty: "medium",
  },
  {
    id: "cer-ch3-13",
    type: "mcq",
    domain: "Microbiology",
    chapter: 3,
    question: "Sepsis has been associated with which of the following endoscopic procedures?",
    options: { a: "Bronchoscopy only", b: "Duodenoscopy only", c: "Upper GI endoscopy only", d: "All of the above" },
    correct: "d",
    explanation: "Sepsis has been associated with bronchoscopy, duodenoscopy, and upper GI endoscopy. Contaminated endoscopes can introduce microorganisms directly into normally sterile body areas, leading to serious systemic infection.",
    difficulty: "medium",
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 4: Work Area Design
  // ═══════════════════════════════════════════════════════════════

  {
    id: "cer-ch4-1",
    type: "mcq",
    domain: "Work Area Design",
    chapter: 4,
    question: "Where should HLD flexible endoscopes be stored?",
    options: { a: "On open wire shelving", b: "In a ventilated cabinet", c: "In a sealed plastic bag", d: "Submerged in sterile water" },
    correct: "b",
    explanation: "HLD flexible endoscopes should be stored in a ventilated cabinet. Sterilized endoscopes may be stored on wire shelving. The ventilated cabinet allows air circulation to keep scopes dry and reduce microbial growth.",
    difficulty: "medium",
  },
  {
    id: "cer-ch4-2",
    type: "mcq",
    domain: "Work Area Design",
    chapter: 4,
    question: "An eye wash station in the decontamination area must be reachable within how many seconds?",
    options: { a: "5 seconds", b: "10 seconds", c: "30 seconds", d: "60 seconds" },
    correct: "b",
    explanation: "The eye wash station must be within 10 seconds of unobstructed travel. It must also deliver 0.4 gallons per minute and provide flushing for a minimum of 15 minutes to adequately remove chemical exposure.",
    difficulty: "medium",
  },
  {
    id: "cer-ch4-3",
    type: "mcq",
    domain: "Work Area Design",
    chapter: 4,
    question: "For how long must an eye wash station continuously flush in the event of a chemical exposure?",
    options: { a: "5 minutes", b: "10 minutes", c: "15 minutes", d: "30 minutes" },
    correct: "c",
    explanation: "Eye wash stations must flush for a minimum of 15 minutes. This extended flushing time is necessary to adequately dilute and remove chemical agents from the eyes and face.",
    difficulty: "hard",
  },
  {
    id: "cer-ch4-4",
    type: "true_false",
    domain: "Work Area Design",
    chapter: 4,
    question: "Bins used to transport soiled endoscopes should be labeled as biohazard.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. Bins used to transport soiled endoscopes must be labeled as biohazard to alert all personnel to the risk of contamination and ensure proper handling procedures are followed during transport.",
    difficulty: "easy",
  },
  {
    id: "cer-ch4-5",
    type: "mcq",
    domain: "Work Area Design",
    chapter: 4,
    question: "Sinks used for endoscope cleaning should be equipped with which two systems?",
    options: { a: "Hot water and drainage", b: "Fill lines and manifold/adaptor systems", c: "UV light and air purification", d: "Filtered water and waste disposal" },
    correct: "b",
    explanation: "Endoscope cleaning sinks should be equipped with fill lines and manifold/adaptor systems. These allow complete submersion of the endoscope and thorough flushing of all internal channels during manual cleaning.",
    difficulty: "hard",
  },
  {
    id: "cer-ch4-6",
    type: "true_false",
    domain: "Work Area Design",
    chapter: 4,
    question: "When airflow is negative, it means air flows INTO that area.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. Negative air pressure means air flows into the area from adjacent spaces. This is used in contaminated/decontamination areas to prevent aerosols from escaping into clean areas.",
    difficulty: "medium",
  },
  {
    id: "cer-ch4-7",
    type: "true_false",
    domain: "Work Area Design",
    chapter: 4,
    question: "The relative humidity in all endoscope work areas should not exceed 60%.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. Relative humidity in all endoscope work areas should not exceed 60%. Excessive humidity can promote microbial growth and affect the integrity of packaging materials and stored items.",
    difficulty: "medium",
  },
  {
    id: "cer-ch4-8",
    type: "mcq",
    domain: "Work Area Design",
    chapter: 4,
    question: "When physical barriers between soiled and clean areas are not possible, what helps assure one-way directional flow?",
    options: { a: "Colored floor markings only", b: "Negative air pressure alone", c: "Education and training of staff", d: "Security cameras" },
    correct: "c",
    explanation: "In the absence of physical barriers, education and training of staff helps assure one-way directional flow. Staff must understand why directional flow matters and consistently follow established traffic patterns.",
    difficulty: "medium",
  },
  {
    id: "cer-ch4-9",
    type: "true_false",
    domain: "Work Area Design",
    chapter: 4,
    question: "Endoscopes that have been high-level disinfected should be stored on open wire shelving.",
    options: { a: "True", b: "False" },
    correct: "b",
    explanation: "False. HLD endoscopes should be stored in ventilated cabinets — not open wire shelving. Open shelving exposes scopes to environmental contaminants and does not provide the protected, ventilated environment needed.",
    difficulty: "medium",
  },
  {
    id: "cer-ch4-10",
    type: "mcq",
    domain: "Work Area Design",
    chapter: 4,
    question: "The automated endoscope reprocessor (AER) should be placed in which work area?",
    options: { a: "The decontamination area to clean scopes before the preparation area", b: "The clean preparation/disinfection area", c: "The storage room adjacent to procedure rooms", d: "Any area with adequate ventilation" },
    correct: "b",
    explanation: "The AER should be placed in the clean preparation/disinfection area — NOT the decontamination area. Scopes must first be manually cleaned in the decontamination area before being placed in the AER.",
    difficulty: "hard",
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 5: Cleaning Basics
  // ═══════════════════════════════════════════════════════════════

  {
    id: "cer-ch5-1",
    type: "mcq",
    domain: "Cleaning Basics & PPE",
    chapter: 5,
    question: "The use of PPE when reprocessing contaminated endoscopes is required by which agency?",
    options: { a: "The Joint Commission", b: "OSHA", c: "FDA", d: "CDC" },
    correct: "b",
    explanation: "OSHA requires the use of PPE when reprocessing contaminated endoscopes under the Bloodborne Pathogen Standard. This is a legal requirement, not just a recommendation.",
    difficulty: "easy",
  },
  {
    id: "cer-ch5-2",
    type: "mcq",
    domain: "Cleaning Basics & PPE",
    chapter: 5,
    question: "What is the correct first step when doffing (removing) personal protective equipment?",
    options: { a: "Remove gloves", b: "Remove the mask", c: "Remove shoe covers", d: "Remove the gown" },
    correct: "c",
    explanation: "Shoe covers are removed first in the doffing sequence. The full order is: shoe covers → gloves → goggles/face shield → gown → mask → head cover → wash hands. This sequence prevents self-contamination.",
    difficulty: "medium",
  },
  {
    id: "cer-ch5-3",
    type: "true_false",
    domain: "Cleaning Basics & PPE",
    chapter: 5,
    question: "Cleaning and decontamination mean the same thing.",
    options: { a: "True", b: "False" },
    correct: "b",
    explanation: "False. Cleaning means the removal of soil from a device. Decontamination means reducing infectious organisms on a device. These are distinct processes — cleaning must occur first to make decontamination effective.",
    difficulty: "easy",
  },
  {
    id: "cer-ch5-4",
    type: "mcq",
    domain: "Cleaning Basics & PPE",
    chapter: 5,
    question: "The most common pH recommended for endoscope cleaning chemicals is:",
    options: { a: "Low pH (acidic)", b: "High pH (alkaline)", c: "Neutral pH", d: "pH is irrelevant for endoscopes" },
    correct: "c",
    explanation: "Neutral pH is the most common recommendation for endoscope cleaning chemicals. Neutral pH cleaners effectively remove soil without damaging the delicate materials and components of endoscopes.",
    difficulty: "medium",
  },
  {
    id: "cer-ch5-5",
    type: "true_false",
    domain: "Cleaning Basics & PPE",
    chapter: 5,
    question: "Detergents used to clean endoscopes should be non-foaming and free-rinsing.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. Endoscope detergents must be non-foaming (to allow fluid contact with all surfaces) and free-rinsing (to prevent residue buildup in channels that could interfere with disinfection or harm patients).",
    difficulty: "medium",
  },
  {
    id: "cer-ch5-6",
    type: "true_false",
    domain: "Cleaning Basics & PPE",
    chapter: 5,
    question: "Household liquid dishwashing detergents are recommended for cleaning gastrointestinal endoscopes.",
    options: { a: "True", b: "False" },
    correct: "b",
    explanation: "False. Household dishwashing detergents are NOT recommended for endoscope cleaning. They may be foaming and not suitable for medical devices. Only detergents cleared for endoscope use and compatible with the manufacturer's IFU should be used.",
    difficulty: "easy",
  },
  {
    id: "cer-ch5-7",
    type: "mcq",
    domain: "Cleaning Basics & PPE",
    chapter: 5,
    question: "At what temperature do enzymatic cleaning solutions become ineffective?",
    options: { a: "Above 100°F", b: "Above 120°F", c: "Above 140°F", d: "Above 160°F" },
    correct: "c",
    explanation: "Enzymatic cleaners become ineffective at temperatures exceeding 140°F. The heat denatures the enzyme proteins, destroying their ability to break down organic soil. Always use water at the recommended temperature.",
    difficulty: "hard",
  },
  {
    id: "cer-ch5-8",
    type: "true_false",
    domain: "Cleaning Basics & PPE",
    chapter: 5,
    question: "Disinfectants must be registered by the EPA before they can be marketed.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. The EPA (Environmental Protection Agency) must register disinfectants before they can be marketed for use as antimicrobial products. EPA registration ensures the product has been evaluated for safety and efficacy.",
    difficulty: "medium",
  },
  {
    id: "cer-ch5-9",
    type: "mcq",
    domain: "Cleaning Basics & PPE",
    chapter: 5,
    question: "One cannot sterilize without first cleaning, but one can disinfect without cleaning.",
    options: { a: "True", b: "False", c: "Only for rigid endoscopes", d: "Only for flexible endoscopes" },
    correct: "b",
    explanation: "False. Cleaning must precede BOTH sterilization AND disinfection. Residual soil on a device blocks disinfectants and sterilants from contacting the microbial load, rendering the process ineffective.",
    difficulty: "medium",
  },
  {
    id: "cer-ch5-10",
    type: "true_false",
    domain: "Cleaning Basics & PPE",
    chapter: 5,
    question: "Solutions that are mixed too strong will not be as effective as solutions mixed to the recommended strength.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. Overly concentrated solutions can be counterproductive — they may damage endoscope materials, leave residues, and are not more effective than properly diluted solutions. Always follow manufacturer concentration instructions.",
    difficulty: "medium",
  },
  {
    id: "cer-ch5-11",
    type: "mcq",
    domain: "Cleaning Basics & PPE",
    chapter: 5,
    question: "Which type of enzyme product is most helpful when cleaning endoscopes?",
    options: { a: "Protease only", b: "Amylase only", c: "Lipase only", d: "Multi-enzyme product" },
    correct: "d",
    explanation: "A multi-enzyme product is most helpful for endoscope cleaning because endoscopes are contaminated with multiple types of organic soil (proteins, carbohydrates, fats, nucleic acids). Multi-enzyme products target all of these simultaneously.",
    difficulty: "medium",
  },
  {
    id: "cer-ch5-12",
    type: "mcq",
    domain: "Cleaning Basics & PPE",
    chapter: 5,
    question: "The specific size brushes needed to clean an endoscope can be found in:",
    options: { a: "OSHA standards", b: "The facility's general policy manual", c: "The manufacturer's Instructions for Use", d: "SGNA guidelines only" },
    correct: "c",
    explanation: "The specific brush sizes required for each endoscope channel are found in the manufacturer's Instructions for Use (IFU). Using the wrong size brush can damage the endoscope or fail to clean adequately.",
    difficulty: "easy",
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 6: Point-of-Use Treatment, Transport & Leak Testing
  // ═══════════════════════════════════════════════════════════════

  {
    id: "cer-ch6-1",
    type: "mcq",
    domain: "Point-of-Use & Leak Testing",
    chapter: 6,
    question: "What is the first step in point-of-use pre-cleaning after removing the endoscope from the patient?",
    options: { a: "Flush channels with water", b: "Move the endoscope away from the patient and remove gross soil", c: "Detach from the light source", d: "Coil and place in container" },
    correct: "b",
    explanation: "The first step is to move the endoscope away from the patient and remove gross soil. This prevents patient exposure and begins the process of removing bioburden before the scope is transported for reprocessing.",
    difficulty: "medium",
  },
  {
    id: "cer-ch6-2",
    type: "true_false",
    domain: "Point-of-Use & Leak Testing",
    chapter: 6,
    question: "Pre-cleaning at the point of use should occur before the endoscope is disconnected from the power source.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. Point-of-use pre-cleaning should begin while the endoscope is still connected to the power source — suctioning cleaning solution through the channels before disconnection helps prevent soil from drying in the channels.",
    difficulty: "medium",
  },
  {
    id: "cer-ch6-3",
    type: "mcq",
    domain: "Point-of-Use & Leak Testing",
    chapter: 6,
    question: "What are the three main goals when transporting a contaminated endoscope?",
    options: { a: "Speed, documentation, and cleanliness", b: "Deliver in a timely manner, prevent cross-contamination, and prevent damage", c: "Seal, label, and notify charge nurse", d: "Document, wrap, and refrigerate" },
    correct: "b",
    explanation: "The three transport goals are: (1) deliver the endoscope in a timely manner to prevent biofilm formation, (2) prevent cross-contamination of the environment, and (3) prevent damage to the delicate endoscope.",
    difficulty: "medium",
  },
  {
    id: "cer-ch6-4",
    type: "true_false",
    domain: "Point-of-Use & Leak Testing",
    chapter: 6,
    question: "After pre-cleaning at the point of use, valves should be reattached to the endoscope for transport to the reprocessing area.",
    options: { a: "True", b: "False" },
    correct: "b",
    explanation: "False. Valves should NOT be reattached to the endoscope for transport. They should be placed in a separate container with the endoscope. Reattaching valves could trap moisture and contamination.",
    difficulty: "medium",
  },
  {
    id: "cer-ch6-5",
    type: "mcq",
    domain: "Point-of-Use & Leak Testing",
    chapter: 6,
    question: "What is the goal of leak testing?",
    options: { a: "Ensure the cleaning solution will not leak out", b: "Ensure all inner channels are full of cleaning solution", c: "Detect damage to the exterior and interior of the endoscope", d: "Confirm the scope is ready for patient use" },
    correct: "c",
    explanation: "The goal of leak testing is to detect damage to the exterior and interior of the endoscope. Undetected damage allows fluid invasion into internal components, causing further damage and potential patient infection.",
    difficulty: "medium",
  },
  {
    id: "cer-ch6-6",
    type: "true_false",
    domain: "Point-of-Use & Leak Testing",
    chapter: 6,
    question: "Leak testing should be performed after point-of-use pre-cleaning, before manual cleaning, and after every procedure.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. Leak testing should be performed at multiple points: after point-of-use pre-cleaning, before manual cleaning, and after every procedure. This ensures damage is detected early and before cleaning solutions are introduced.",
    difficulty: "medium",
  },
  {
    id: "cer-ch6-7",
    type: "true_false",
    domain: "Point-of-Use & Leak Testing",
    chapter: 6,
    question: "When performing a leak test, the water-resistant cap should be removed.",
    options: { a: "True", b: "False" },
    correct: "b",
    explanation: "False. The water-resistant cap should NOT be removed during a leak test. The cap protects sensitive internal components from water damage while the endoscope is pressurized during the leak test.",
    difficulty: "medium",
  },
  {
    id: "cer-ch6-8",
    type: "mcq",
    domain: "Point-of-Use & Leak Testing",
    chapter: 6,
    question: "When cleaning an endoscope that has a minor leak, how long should the endoscope be depressurized before proceeding?",
    options: { a: "10 seconds", b: "30 seconds", c: "1 minute", d: "5 minutes" },
    correct: "b",
    explanation: "After removing a leaking endoscope from water, the leak tester should be turned off or the control valve opened, and the endoscope allowed to depressurize for approximately 30 seconds before cleaning the affected area.",
    difficulty: "hard",
  },
  {
    id: "cer-ch6-9",
    type: "true_false",
    domain: "Point-of-Use & Leak Testing",
    chapter: 6,
    question: "Endoscopes with major leaks cannot be cleaned before being sent out for repair.",
    options: { a: "True", b: "False" },
    correct: "b",
    explanation: "False. Even endoscopes with major leaks must be cleaned before being sent out for repair to make them safe to handle for repair technicians. The cleaning method used should be documented.",
    difficulty: "hard",
  },
  {
    id: "cer-ch6-10",
    type: "mcq",
    domain: "Point-of-Use & Leak Testing",
    chapter: 6,
    question: "Where should accessories such as forceps and snare wires be placed when transporting a contaminated endoscope?",
    options: { a: "In the same container as the endoscope", b: "In a separate container transported with the endoscope", c: "Left at the bedside", d: "Disposed of after each use" },
    correct: "b",
    explanation: "Accessories should be placed in a SEPARATE container and transported with the endoscope. Placing them in the same container as the scope could cause damage to the endoscope's delicate external surface.",
    difficulty: "medium",
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 7: Cleaning Processes for Flexible Endoscopes
  // ═══════════════════════════════════════════════════════════════

  {
    id: "cer-ch7-1",
    type: "mcq",
    domain: "Manual Cleaning Processes",
    chapter: 7,
    question: "How many steps outline the manual cleaning process for flexible endoscopes?",
    options: { a: "Four", b: "Five", c: "Seven", d: "Ten" },
    correct: "c",
    explanation: "The seven manual cleaning steps are: (1) submerge in detergent, (2) clean all surfaces manually, (3) attach recommended cleaning adaptors, (4) flush channels with detergent, (5) soak for recommended time, (6) rinse in clean water, (7) remove water by flushing with air.",
    difficulty: "medium",
  },
  {
    id: "cer-ch7-2",
    type: "true_false",
    domain: "Manual Cleaning Processes",
    chapter: 7,
    question: "Manual cleaning should begin immediately after pre-cleaning, with no delay.",
    options: { a: "True", b: "False" },
    correct: "b",
    explanation: "False. Manual cleaning should NOT begin immediately after pre-cleaning — leak testing must be performed first. The correct order is: pre-cleaning → leak testing → manual cleaning.",
    difficulty: "medium",
  },
  {
    id: "cer-ch7-3",
    type: "mcq",
    domain: "Manual Cleaning Processes",
    chapter: 7,
    question: "What are the dangers of delayed reprocessing of endoscopes?",
    options: { a: "Only cosmetic staining", b: "Biofilms form and soil dries, making cleaning more difficult", c: "The endoscope becomes sterile over time", d: "Only external surfaces are affected" },
    correct: "b",
    explanation: "Delayed reprocessing allows biofilms to form and soil to dry. Both conditions make cleaning significantly more difficult and increase infection risk. Reprocessing should begin as soon as possible after use.",
    difficulty: "medium",
  },
  {
    id: "cer-ch7-4",
    type: "true_false",
    domain: "Manual Cleaning Processes",
    chapter: 7,
    question: "Automated cleaning is the most important step in removing microbial bioburden from a flexible endoscope.",
    options: { a: "True", b: "False" },
    correct: "b",
    explanation: "False. Manual cleaning is the most important step in removing microbial bioburden. Automated reprocessors do not replace thorough manual cleaning — they must be preceded by it. The mechanical action of manual cleaning physically removes the majority of bioburden.",
    difficulty: "medium",
  },
  {
    id: "cer-ch7-5",
    type: "mcq",
    domain: "Manual Cleaning Processes",
    chapter: 7,
    question: "Which type of cleaning brush offers the safest way to minimize cross-contamination risks?",
    options: { a: "Reusable stiff-bristled brushes", b: "Reusable soft nylon brushes", c: "Disposable brushes", d: "Metal wire brushes" },
    correct: "c",
    explanation: "Disposable brushes offer the safest and easiest way to minimize cross-contamination risks. Reusable brushes require their own cleaning and disinfection between uses, adding complexity and potential for error.",
    difficulty: "easy",
  },
  {
    id: "cer-ch7-6",
    type: "true_false",
    domain: "Manual Cleaning Processes",
    chapter: 7,
    question: "When manually cleaning endoscopes, the cleaning solution should be changed for each endoscope.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. The cleaning solution should be changed for each endoscope. Reusing cleaning solution transfers soil from one scope to another and reduces the effectiveness of the detergent.",
    difficulty: "medium",
  },
  {
    id: "cer-ch7-7",
    type: "true_false",
    domain: "Manual Cleaning Processes",
    chapter: 7,
    question: "When cleaning the lumens of an endoscope, the brush should be rinsed before pulling it back through the channel.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. The brush should be rinsed before pulling it back through the channel to remove the soil collected on the brush tip. Pulling a soil-laden brush back through deposits contamination in the channel.",
    difficulty: "medium",
  },
  {
    id: "cer-ch7-8",
    type: "mcq",
    domain: "Manual Cleaning Processes",
    chapter: 7,
    question: "After rinsing and before disinfection, inner channels should be:",
    options: { a: "Flushed with clear water only", b: "Purged with air only", c: "Dried with a lint-free cloth", d: "Flushed with clear water, purged with air, and dried" },
    correct: "d",
    explanation: "After rinsing but before disinfection, inner channels should be flushed with clear water, purged with air, and dried. This removes all water to prevent dilution of the disinfectant and reduces microbial growth opportunity.",
    difficulty: "medium",
  },
  {
    id: "cer-ch7-9",
    type: "true_false",
    domain: "Manual Cleaning Processes",
    chapter: 7,
    question: "Thorough manual cleaning must be performed before placing an endoscope into an automated equipment reprocessor.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. Thorough manual cleaning must always precede AER use. The AER is not a substitute for manual cleaning — it supplements it. Without prior manual cleaning, the AER cannot achieve adequate disinfection.",
    difficulty: "easy",
  },
  {
    id: "cer-ch7-10",
    type: "true_false",
    domain: "Manual Cleaning Processes",
    chapter: 7,
    question: "Enzymatic cleaning solution used for endoscope cleaning should be discarded after each use.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. Enzymatic cleaning solution should be discarded after each use. Reusing the solution introduces cross-contamination between scopes and depletes enzymatic activity, reducing cleaning effectiveness.",
    difficulty: "medium",
  },
  {
    id: "cer-ch7-11",
    type: "mcq",
    domain: "Manual Cleaning Processes",
    chapter: 7,
    question: "Reprocessing that begins more than one hour after the endoscope is used is called:",
    options: { a: "Pre-cleaning", b: "Manual cleaning", c: "Delayed processing", d: "Extended reprocessing" },
    correct: "c",
    explanation: "Reprocessing that begins more than one hour after use is called delayed processing. This creates significant challenges because biofilm begins forming and soil dries, both of which make cleaning more difficult.",
    difficulty: "medium",
  },
  {
    id: "cer-ch7-12",
    type: "true_false",
    domain: "Manual Cleaning Processes",
    chapter: 7,
    question: "All removable parts of an endoscope should be carefully cleaned using a stiff-bristled brush.",
    options: { a: "True", b: "False" },
    correct: "b",
    explanation: "False. Removable parts should be carefully cleaned, but stiff-bristled brushes can damage delicate endoscope components. Use appropriately sized and stiffness-rated brushes per the manufacturer's IFU.",
    difficulty: "medium",
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 8: Endoscope Inspection and Preparation
  // ═══════════════════════════════════════════════════════════════

  {
    id: "cer-ch8-1",
    type: "mcq",
    domain: "Inspection & Preparation",
    chapter: 8,
    question: "What do dark spots at the end of a fiber optic light cord indicate?",
    options: { a: "The cord needs cleaning", b: "Broken light fibers", c: "Normal appearance", d: "Excessive heat damage to the casing" },
    correct: "b",
    explanation: "Dark spots at the end of a fiber optic light cord indicate broken light fibers. Each dark spot represents a fiber that is no longer transmitting light, reducing illumination quality and indicating the cord should be repaired or replaced.",
    difficulty: "medium",
  },
  {
    id: "cer-ch8-2",
    type: "true_false",
    domain: "Inspection & Preparation",
    chapter: 8,
    question: "Using a borescope to examine an endoscope lumen can help detect soil and damage.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. A borescope can be inserted into endoscope channels to visually inspect for soil and damage that cannot be seen with the naked eye. This is an important quality verification step in the reprocessing workflow.",
    difficulty: "easy",
  },
  {
    id: "cer-ch8-3",
    type: "true_false",
    domain: "Inspection & Preparation",
    chapter: 8,
    question: "Venting caps are designed to prevent pressure buildup inside the endoscope.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. Venting caps prevent harmful pressure buildup inside the endoscope during sterilization processes. Without proper venting, pressure differentials can rupture the endoscope sheath.",
    difficulty: "medium",
  },
  {
    id: "cer-ch8-4",
    type: "mcq",
    domain: "Inspection & Preparation",
    chapter: 8,
    question: "How many times should flexible endoscopes be visually inspected?",
    options: { a: "Twice — before and after use", b: "Three times — before, during, and after use", c: "Four times — before, after, after cleaning, and before HLD", d: "Five times — before use, during use, after use, after cleaning, and before HLD/sterilization" },
    correct: "d",
    explanation: "Flexible endoscopes should be visually inspected five times: before use, during use, after use, after cleaning, and before HLD or sterilization. Multiple inspection points ensure damage is caught at every stage.",
    difficulty: "hard",
  },
  {
    id: "cer-ch8-5",
    type: "true_false",
    domain: "Inspection & Preparation",
    chapter: 8,
    question: "When preparing a flexible endoscope for HLD, it is important to put the valve cover back on to ensure the disinfectant can enter the lumens.",
    options: { a: "True", b: "False" },
    correct: "b",
    explanation: "False. Valve covers should NOT be replaced before HLD. For high-level disinfection, lumens should be open and detachable components removed so the disinfectant can reach all surfaces inside the channels.",
    difficulty: "medium",
  },
  {
    id: "cer-ch8-6",
    type: "true_false",
    domain: "Inspection & Preparation",
    chapter: 8,
    question: "If soil is detected while inspecting an endoscope, the endoscope must be reprocessed.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. If soil is detected during inspection, the endoscope must be reprocessed from the beginning of the cleaning cycle. Proceeding to disinfection with visible soil present would result in inadequate disinfection.",
    difficulty: "easy",
  },
  {
    id: "cer-ch8-7",
    type: "mcq",
    domain: "Inspection & Preparation",
    chapter: 8,
    question: "Using poor technique or skipping leak testing can cause which problem?",
    options: { a: "Only regulatory citation issues", b: "Harm to the patient", c: "Only equipment damage", d: "Only scheduling delays" },
    correct: "b",
    explanation: "Using poor technique or skipping leak testing can directly cause harm to the patient. Damaged endoscopes that have not been properly leak tested can harbor contamination and fail during use.",
    difficulty: "easy",
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 9: Disinfection Processes for Flexible Endoscopes
  // ═══════════════════════════════════════════════════════════════

  {
    id: "cer-ch9-1",
    type: "mcq",
    domain: "Disinfection Processes",
    chapter: 9,
    question: "How many general steps are in the manual disinfection process for endoscopes?",
    options: { a: "5", b: "7", c: "10", d: "13" },
    correct: "c",
    explanation: "The 10 steps are: (1) pre-cleaning at point of use, (2) transporting, (3) leak testing, (4) cleaning, (5) rinsing, (6) inspecting/testing for cleanliness, (7) HLD/disinfection, (8) rinsing, (9) drying/alcohol flush, (10) storage.",
    difficulty: "hard",
  },
  {
    id: "cer-ch9-2",
    type: "true_false",
    domain: "Disinfection Processes",
    chapter: 9,
    question: "All endoscopes should be high-level disinfected or sterilized between each patient.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. All endoscopes must be high-level disinfected or sterilized between each patient use. This is a non-negotiable standard that prevents transmission of infectious agents from patient to patient.",
    difficulty: "easy",
  },
  {
    id: "cer-ch9-3",
    type: "mcq",
    domain: "Disinfection Processes",
    chapter: 9,
    question: "Why must excess water be removed from endoscopes before soaking in HLD?",
    options: { a: "To prevent rust on metal components", b: "To minimize dilution of the disinfectant", c: "To allow the endoscope to float properly", d: "To prevent overheating" },
    correct: "b",
    explanation: "Excess water must be removed to minimize dilution of the high-level disinfectant. Dilution can drop the concentration below the minimum effective concentration, compromising the ability to kill pathogens.",
    difficulty: "medium",
  },
  {
    id: "cer-ch9-4",
    type: "true_false",
    domain: "Disinfection Processes",
    chapter: 9,
    question: "If an HLD test fails to reach minimum recommended concentration, more disinfectant should be added to raise the concentration before use.",
    options: { a: "True", b: "False" },
    correct: "b",
    explanation: "False. If the HLD solution fails to reach minimum recommended concentration, it must be DISCARDED. Adding more disinfectant to a depleted solution does not restore its original efficacy because other chemical components have also degraded.",
    difficulty: "medium",
  },
  {
    id: "cer-ch9-5",
    type: "true_false",
    domain: "Disinfection Processes",
    chapter: 9,
    question: "Endoscopes are considered semi-critical devices.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. Endoscopes are classified as semi-critical devices because they contact mucous membranes but typically do not penetrate sterile tissue. Semi-critical devices require at minimum high-level disinfection.",
    difficulty: "medium",
  },
  {
    id: "cer-ch9-6",
    type: "mcq",
    domain: "Disinfection Processes",
    chapter: 9,
    question: "Failing to dry an endoscope properly after HLD and rinsing can allow:",
    options: { a: "Chemical buildup", b: "Recontamination of the endoscope", c: "Damage to the outer sheath", d: "HLD solution to remain active" },
    correct: "b",
    explanation: "Failing to properly dry an endoscope after HLD and rinsing can allow for recontamination of the endoscope. Residual moisture supports microbial growth during storage, undoing the work of reprocessing.",
    difficulty: "medium",
  },
  {
    id: "cer-ch9-7",
    type: "true_false",
    domain: "Disinfection Processes",
    chapter: 9,
    question: "Automated endoscope reprocessor device connectors are designed for use with any flexible endoscope.",
    options: { a: "True", b: "False" },
    correct: "b",
    explanation: "False. AER device connectors are NOT universal. They are designed for specific endoscope models. Using the wrong connector can result in channels not being properly flushed, leading to inadequate disinfection.",
    difficulty: "medium",
  },
  {
    id: "cer-ch9-8",
    type: "true_false",
    domain: "Disinfection Processes",
    chapter: 9,
    question: "When using an AER with an automated cleaning cycle, it is still necessary to thoroughly manually clean the endoscope first.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. Even when using an AER with an automated cleaning cycle, thorough manual cleaning must be performed first. The AER's cleaning cycle does not replace manual cleaning — it supplements it.",
    difficulty: "medium",
  },
  {
    id: "cer-ch9-9",
    type: "mcq",
    domain: "Disinfection Processes",
    chapter: 9,
    question: "The high-level disinfectant solution in an AER should be tested for minimum effective concentration:",
    options: { a: "Daily", b: "Each shift", c: "Before each use", d: "Weekly" },
    correct: "c",
    explanation: "The HLD solution in an AER should be tested for minimum effective concentration before each use. This ensures every reprocessing cycle uses solution that meets the required concentration for efficacy.",
    difficulty: "hard",
  },
  {
    id: "cer-ch9-10",
    type: "mcq",
    domain: "Disinfection Processes",
    chapter: 9,
    question: "The minimum effective concentration (MEC) and minimum recommended concentration (MRC) of high-level disinfectants mean the same thing.",
    options: { a: "True", b: "False", c: "Only for glutaraldehyde products", d: "Only for OPA products" },
    correct: "b",
    explanation: "False. MEC and MRC are different. The MEC is the lowest concentration at which the product still has antimicrobial efficacy. The MRC is the manufacturer's recommended concentration for use. The MRC is typically higher than the MEC.",
    difficulty: "hard",
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 10: Sterilization Processes
  // ═══════════════════════════════════════════════════════════════

  {
    id: "cer-ch10-1",
    type: "mcq",
    domain: "Sterilization Processes",
    chapter: 10,
    question: "Which of the following can result in a sterilization failure?",
    options: { a: "Using a new sterilizer with fresh biological indicators", b: "Improper sterilizer loading", c: "Running a full load", d: "Using biological indicators in every cycle" },
    correct: "b",
    explanation: "Sterilization failures can be caused by: improper loading, device design challenges, too much soil, or too many microorganisms. Improper loading is one of the most common preventable causes.",
    difficulty: "medium",
  },
  {
    id: "cer-ch10-2",
    type: "mcq",
    domain: "Sterilization Processes",
    chapter: 10,
    question: "What are the four critical parameters of ethylene oxide (EtO) sterilization?",
    options: {
      a: "Temperature, pressure, humidity, and load size",
      b: "Cycle temperature, relative humidity at end of conditioning, EtO gas exposure time, and EtO concentration",
      c: "Pre-vacuum, exposure, drying, and aeration",
      d: "Temperature, chemical indicator, biological indicator, and load weight",
    },
    correct: "b",
    explanation: "The four critical parameters of EtO sterilization are: (1) cycle temperature, (2) relative humidity at the end of conditioning, (3) ethylene oxide gas exposure time, and (4) ethylene oxide concentration. All four must be met for sterilization assurance.",
    difficulty: "hard",
  },
  {
    id: "cer-ch10-3",
    type: "true_false",
    domain: "Sterilization Processes",
    chapter: 10,
    question: "Cellulose-containing materials are acceptable packaging for hydrogen peroxide plasma sterilization.",
    options: { a: "True", b: "False" },
    correct: "b",
    explanation: "False. Cellulose-containing materials (paper, muslin) are NOT acceptable for hydrogen peroxide plasma sterilization. Cellulose absorbs the hydrogen peroxide, depleting the sterilant and preventing adequate sterilization.",
    difficulty: "hard",
  },
  {
    id: "cer-ch10-4",
    type: "mcq",
    domain: "Sterilization Processes",
    chapter: 10,
    question: "The daily test used to validate the vacuum cycle of a steam sterilizer is called the:",
    options: { a: "Biological indicator test", b: "Chemical indicator test", c: "Bowie Dick test", d: "HEPA filtration test" },
    correct: "c",
    explanation: "The Bowie Dick test is run daily on pre-vacuum steam sterilizers to validate that air is being properly removed from the chamber. Adequate air removal is essential for steam to penetrate packaged items.",
    difficulty: "medium",
  },
  {
    id: "cer-ch10-5",
    type: "true_false",
    domain: "Sterilization Processes",
    chapter: 10,
    question: "After ethylene oxide sterilization, items must undergo aeration to remove toxic residuals.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. After EtO sterilization, items must undergo aeration — exposure to moving air to remove toxic EtO residuals. Insufficiently aerated items can cause chemical burns to patient tissue.",
    difficulty: "medium",
  },
  {
    id: "cer-ch10-6",
    type: "true_false",
    domain: "Sterilization Processes",
    chapter: 10,
    question: "When the color of chemical indicator tape used to seal flat wrap changes, it indicates the item is sterile.",
    options: { a: "True", b: "False" },
    correct: "b",
    explanation: "False. A color change in chemical indicator tape only indicates that the package was exposed to a sterilization process — NOT that sterility was achieved. Only biological indicators provide assurance of sterility.",
    difficulty: "medium",
  },
  {
    id: "cer-ch10-7",
    type: "mcq",
    domain: "Sterilization Processes",
    chapter: 10,
    question: "Which sterilization method requires OSHA to mandate a method to alert employees to emergency situations?",
    options: { a: "Steam sterilization", b: "Hydrogen peroxide plasma", c: "Ethylene oxide", d: "Dry heat" },
    correct: "c",
    explanation: "OSHA requires facilities using ethylene oxide sterilization to have a method to alert employees to emergency situations. EtO is a toxic, flammable gas that poses significant health and safety risks to workers.",
    difficulty: "hard",
  },
  {
    id: "cer-ch10-8",
    type: "true_false",
    domain: "Sterilization Processes",
    chapter: 10,
    question: "Most multi-part flexible endoscopes and their accessories must be disassembled for sterilization.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. Most multi-part flexible endoscopes must be disassembled before sterilization. Assembled devices can trap air or soil and prevent the sterilant from reaching all surfaces.",
    difficulty: "medium",
  },
  {
    id: "cer-ch10-9",
    type: "mcq",
    domain: "Sterilization Processes",
    chapter: 10,
    question: "Terminal sterilization refers to which process?",
    options: { a: "Immediate Use Steam Sterilization", b: "Sterilization of items in their final containers for storage until use", c: "The final stage of aeration", d: "Emergency sterilization of a single item" },
    correct: "b",
    explanation: "Terminal sterilization is the process of sterilizing medical devices in their final containers, allowing them to be stored until needed. This is the preferred method as it maintains sterility through storage and transport.",
    difficulty: "medium",
  },
  {
    id: "cer-ch10-10",
    type: "true_false",
    domain: "Sterilization Processes",
    chapter: 10,
    question: "A biological indicator should be run in each ethylene oxide sterilization cycle.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. A biological indicator must be run in each EtO sterilization cycle. EtO sterilization requires biological indicator monitoring for every cycle because of its complexity, the toxicity of the agent, and the challenges of monitoring the process.",
    difficulty: "medium",
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 11: Endoscope Handling, Storage and Transport
  // ═══════════════════════════════════════════════════════════════

  {
    id: "cer-ch11-1",
    type: "true_false",
    domain: "Handling, Storage & Transport",
    chapter: 11,
    question: "Hang time for flexible endoscopes should be determined after a risk assessment has been conducted.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. Hang time (storage time before reprocessing is required) should be determined by each facility following a risk assessment. Factors include storage environment, how the scope is stored, and the patient population.",
    difficulty: "medium",
  },
  {
    id: "cer-ch11-2",
    type: "mcq",
    domain: "Handling, Storage & Transport",
    chapter: 11,
    question: "Which three items should be documented on an endoscope storage tag?",
    options: {
      a: "Endoscope serial number, model, and repair history",
      b: "Date processed, date HLD was performed, and technician identification",
      c: "Patient name, procedure type, and physician",
      d: "Storage location, shelf number, and expiration",
    },
    correct: "b",
    explanation: "An endoscope storage tag should document: (1) date processed, (2) date HLD was performed, and (3) the technician's identification. This supports traceability for patient notification if a processing failure is discovered.",
    difficulty: "medium",
  },
  {
    id: "cer-ch11-3",
    type: "true_false",
    domain: "Handling, Storage & Transport",
    chapter: 11,
    question: "Moisture remaining in an endoscope after reprocessing provides an opportunity for bacteria to grow.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. Residual moisture inside endoscope channels after reprocessing provides an ideal environment for bacterial growth during storage. Thorough drying including alcohol flushing of channels is essential.",
    difficulty: "easy",
  },
  {
    id: "cer-ch11-4",
    type: "true_false",
    domain: "Handling, Storage & Transport",
    chapter: 11,
    question: "Endoscope components should be kept with the same endoscope so they can be located in the event of a recall.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. Keeping an endoscope and all its components together ensures they can all be located in the event of a recall. Traceability is critical so that patients who were exposed to a compromised scope can be notified.",
    difficulty: "easy",
  },
  {
    id: "cer-ch11-5",
    type: "true_false",
    domain: "Handling, Storage & Transport",
    chapter: 11,
    question: "Endoscopes should always be stored vertically.",
    options: { a: "True", b: "False" },
    correct: "b",
    explanation: "False. Endoscopes should generally be stored in a hanging vertical position to allow drainage and airflow, but should NOT always be stored vertically. The manufacturer's IFU specifies the correct storage position for each device.",
    difficulty: "medium",
  },
  {
    id: "cer-ch11-6",
    type: "mcq",
    domain: "Handling, Storage & Transport",
    chapter: 11,
    question: "Sterilized flexible endoscopes should be stored in the same manner as:",
    options: { a: "HLD endoscopes in ventilated cabinets", b: "Other sterilized devices", c: "Unused new endoscopes", d: "Disposable single-use devices" },
    correct: "b",
    explanation: "Sterilized flexible endoscopes should be stored in the same manner as other sterilized devices — in sterile storage conditions that protect packaging integrity and maintain sterility until use.",
    difficulty: "medium",
  },
  {
    id: "cer-ch11-7",
    type: "true_false",
    domain: "Handling, Storage & Transport",
    chapter: 11,
    question: "Filtered air in storage areas helps reduce the risk of contamination during endoscope storage.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. Filtered air in storage areas helps reduce the risk of airborne contamination of stored endoscopes. Ventilated storage cabinets with filtered air provide the best protection for HLD endoscopes.",
    difficulty: "medium",
  },
  {
    id: "cer-ch11-8",
    type: "true_false",
    domain: "Handling, Storage & Transport",
    chapter: 11,
    question: "When storing flexible endoscopes, the terms 'expiration date' and 'hang time' mean the same thing.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. In the context of endoscope storage, 'expiration date' and 'hang time' refer to the same concept — the date after which a stored HLD endoscope must be reprocessed before use.",
    difficulty: "medium",
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 12: Rigid and Semi-Rigid Endoscopes
  // ═══════════════════════════════════════════════════════════════

  {
    id: "cer-ch12-1",
    type: "mcq",
    domain: "Rigid & Semi-Rigid Endoscopes",
    chapter: 12,
    question: "An arthroscope is used for surgeries on which part of the body?",
    options: { a: "Abdominal organs", b: "Nasal passages", c: "Joints", d: "Kidneys" },
    correct: "c",
    explanation: "An arthroscope is used for surgeries on joints (knees, shoulders, hips, etc.). It allows visualization and treatment through small incisions, reducing recovery time compared to open surgery.",
    difficulty: "easy",
  },
  {
    id: "cer-ch12-2",
    type: "mcq",
    domain: "Rigid & Semi-Rigid Endoscopes",
    chapter: 12,
    question: "Which endoscope is used to examine the urethra, bladder, and prostate?",
    options: { a: "Nephroscope", b: "Ureteroscope", c: "Cystoscope", d: "Hysteroscope" },
    correct: "c",
    explanation: "The cystoscope is used to examine the urethra, bladder, and prostate. It allows direct visualization of the lower urinary tract for diagnosis and treatment of conditions like bladder stones, tumors, and strictures.",
    difficulty: "medium",
  },
  {
    id: "cer-ch12-3",
    type: "true_false",
    domain: "Rigid & Semi-Rigid Endoscopes",
    chapter: 12,
    question: "The objective lens of a rigid endoscope is the strongest part of the endoscope.",
    options: { a: "True", b: "False" },
    correct: "b",
    explanation: "False. The objective lens is actually the most fragile and easily damaged part of a rigid endoscope. It is located at the distal end and is susceptible to damage from dropping, bending, and excessive heat.",
    difficulty: "medium",
  },
  {
    id: "cer-ch12-4",
    type: "mcq",
    domain: "Rigid & Semi-Rigid Endoscopes",
    chapter: 12,
    question: "Rigid endoscope rod lenses are made from:",
    options: { a: "Fiber optics", b: "Reflective metal rods", c: "Glass", d: "High-density prisms" },
    correct: "c",
    explanation: "Rod lenses in rigid endoscopes are made from glass. The Hopkins rod lens system uses precisely ground glass rods to transmit a high-quality image from the distal tip to the eyepiece.",
    difficulty: "medium",
  },
  {
    id: "cer-ch12-5",
    type: "true_false",
    domain: "Rigid & Semi-Rigid Endoscopes",
    chapter: 12,
    question: "Rigid endoscopes that are approved for steam sterilization can also be Immediate Use Steam Sterilized.",
    options: { a: "True", b: "False" },
    correct: "b",
    explanation: "False. Approval for standard steam sterilization does not automatically qualify an endoscope for Immediate Use Steam Sterilization (IUSS). IUSS requires specific manufacturer validation as a separate designation.",
    difficulty: "hard",
  },
  {
    id: "cer-ch12-6",
    type: "mcq",
    domain: "Rigid & Semi-Rigid Endoscopes",
    chapter: 12,
    question: "Rigid endoscope lens damage can easily occur from:",
    options: { a: "Exposure to enzymatic cleaners", b: "Dropping, bending, and exposure to excessive heat", c: "Using low pH cleaning solutions only", d: "Prolonged storage" },
    correct: "b",
    explanation: "Rigid endoscope lens damage commonly occurs from dropping (impact), bending (stress on the glass), and exposure to excessive heat. All handling and processing procedures must account for this fragility.",
    difficulty: "medium",
  },
  {
    id: "cer-ch12-7",
    type: "true_false",
    domain: "Rigid & Semi-Rigid Endoscopes",
    chapter: 12,
    question: "Using the wrong size light cable can cause damage to a rigid endoscope.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. Light cables for rigid endoscopes come in different sizes and are not interchangeable. Using a cable that doesn't match the endoscope can damage the light post connector and reduce image quality.",
    difficulty: "medium",
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 13: Endoscope System Maintenance
  // ═══════════════════════════════════════════════════════════════

  {
    id: "cer-ch13-1",
    type: "mcq",
    domain: "System Maintenance",
    chapter: 13,
    question: "Which of the following is NOT one of the five goals of an endoscope system maintenance program?",
    options: { a: "Protect endoscopes from damage", b: "Perform all repairs in-house", c: "Track and document repairs", d: "Ensure prompt and appropriate repairs" },
    correct: "b",
    explanation: "The five goals are: protect from damage, routinely inspect and test, ensure prompt/appropriate repairs, receive endoscopes properly into the system, and track/document repairs. In-house repair is not a goal — many repairs require specialized service companies.",
    difficulty: "medium",
  },
  {
    id: "cer-ch13-2",
    type: "mcq",
    domain: "System Maintenance",
    chapter: 13,
    question: "When sending a damaged endoscope out for repair, the two main considerations are:",
    options: {
      a: "Cost and turnaround time",
      b: "Make the endoscope safe to handle and prevent further damage",
      c: "Documentation and insurance pre-authorization",
      d: "Cleaning level and packaging material type",
    },
    correct: "b",
    explanation: "The two main considerations are: (1) making the endoscope safe to handle for repair technicians, and (2) preventing further damage during packaging and shipping. Both protect the repair technicians and preserve the scope.",
    difficulty: "medium",
  },
  {
    id: "cer-ch13-3",
    type: "true_false",
    domain: "System Maintenance",
    chapter: 13,
    question: "When a loaned endoscope arrives at a facility, it should be inspected, tested, and reprocessed per its IFU before being placed into service.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. Loaned endoscopes must be fully inspected, tested, and reprocessed according to that specific endoscope's IFU before use — even if they appear clean. Their processing history is unknown.",
    difficulty: "medium",
  },
  {
    id: "cer-ch13-4",
    type: "true_false",
    domain: "System Maintenance",
    chapter: 13,
    question: "When preparing a damaged endoscope for shipment, including a description of the problem is not necessary because the service company will inspect it.",
    options: { a: "True", b: "False" },
    correct: "b",
    explanation: "False. Including a description of the problem is important and necessary when shipping a damaged endoscope. This information helps the service company prioritize and address the specific issue efficiently.",
    difficulty: "medium",
  },
  {
    id: "cer-ch13-5",
    type: "mcq",
    domain: "System Maintenance",
    chapter: 13,
    question: "An action plan must include which three elements?",
    options: {
      a: "Budget, signatures, and timeline",
      b: "Identify specific tasks, set a time horizon for completion, and identify/allocate needed resources",
      c: "Problem statement, risk analysis, and cost estimate",
      d: "Staff list, training dates, and audit schedule",
    },
    correct: "b",
    explanation: "An action plan must: (1) identify specific tasks (what will be done and by whom), (2) set a time horizon for completion, and (3) identify and allocate the resources needed to accomplish the tasks.",
    difficulty: "medium",
  },
  {
    id: "cer-ch13-6",
    type: "true_false",
    domain: "System Maintenance",
    chapter: 13,
    question: "Surveyors may ask staff in the endoscope reprocessing area to demonstrate department protocols for damaged endoscopes.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. Regulatory surveyors (such as CMS surveyors and Joint Commission inspectors) may ask reprocessing staff to demonstrate protocols for damaged endoscopes. Staff must be competent and ready to demonstrate procedures.",
    difficulty: "medium",
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 14: Regulations, Standards and Resources
  // ═══════════════════════════════════════════════════════════════

  {
    id: "cer-ch14-1",
    type: "mcq",
    domain: "Regulations & Standards",
    chapter: 14,
    question: "Which agency administers HIPAA standards?",
    options: { a: "OSHA", b: "FDA", c: "CMS", d: "EPA" },
    correct: "c",
    explanation: "CMS (Centers for Medicare and Medicaid Services) administers HIPAA standards. CMS surveyors also ask facilities about duodenoscope reprocessing and are responsible for loss of federal funding if standards are not met.",
    difficulty: "medium",
  },
  {
    id: "cer-ch14-2",
    type: "mcq",
    domain: "Regulations & Standards",
    chapter: 14,
    question: "Which organization developed ST79 and ST91, two important standards for endoscope reprocessing?",
    options: { a: "CDC", b: "AAMI", c: "SGNA", d: "OSHA" },
    correct: "b",
    explanation: "AAMI (Association for the Advancement of Medical Instrumentation) developed and released ST79 (comprehensive guide to steam sterilization) and ST91 (flexible and semi-rigid endoscope reprocessing). AAMI is the non-profit organization that writes standards and technical information reports.",
    difficulty: "medium",
  },
  {
    id: "cer-ch14-3",
    type: "true_false",
    domain: "Regulations & Standards",
    chapter: 14,
    question: "When federal and state reprocessing requirements differ, facilities must follow the most stringent requirements.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. When federal and state regulations differ, facilities must follow the MORE STRINGENT requirement — regardless of whether it comes from the state or federal level. This protects patients with the highest applicable standard.",
    difficulty: "medium",
  },
  {
    id: "cer-ch14-4",
    type: "mcq",
    domain: "Regulations & Standards",
    chapter: 14,
    question: "Which agency enforces the Bloodborne Pathogen Standard?",
    options: { a: "FDA", b: "CDC", c: "OSHA", d: "EPA" },
    correct: "c",
    explanation: "OSHA enforces the Bloodborne Pathogen Standard, which requires employers to protect workers from exposure to blood and other potentially infectious materials through engineering controls, PPE, training, and exposure control plans.",
    difficulty: "easy",
  },
  {
    id: "cer-ch14-5",
    type: "true_false",
    domain: "Regulations & Standards",
    chapter: 14,
    question: "The CDC published the document 'Essential Elements of a Reprocessing Program for Flexible Endoscopes.'",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. The CDC published 'Essential Elements of a Reprocessing Program for Flexible Endoscopes.' The CDC also provides guidelines on infection prevention and PPE usage that are relevant to endoscope reprocessing.",
    difficulty: "medium",
  },
  {
    id: "cer-ch14-6",
    type: "mcq",
    domain: "Regulations & Standards",
    chapter: 14,
    question: "Which agency regulates the transporting of minimally processed items outside of healthcare facilities?",
    options: { a: "FDA", b: "OSHA", c: "DOT", d: "CMS" },
    correct: "c",
    explanation: "DOT (Department of Transportation) regulates the transport of minimally processed/hazardous items outside of healthcare facilities. This includes requirements for proper labeling and containment of biohazardous materials.",
    difficulty: "hard",
  },
  {
    id: "cer-ch14-7",
    type: "true_false",
    domain: "Regulations & Standards",
    chapter: 14,
    question: "Failure to comply with regulatory standards may lead to fines.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. Failure to comply with regulatory standards may lead to fines and other consequences including loss of accreditation, loss of Medicare/Medicaid funding, and legal liability. Compliance is not optional.",
    difficulty: "easy",
  },
  {
    id: "cer-ch14-8",
    type: "mcq",
    domain: "Regulations & Standards",
    chapter: 14,
    question: "Which agency requires manufacturers to provide Instructions for Use (IFU) with each medical device?",
    options: { a: "OSHA", b: "EPA", c: "AAMI", d: "FDA" },
    correct: "d",
    explanation: "The FDA requires manufacturers to provide Instructions for Use (IFU) with each medical device. The IFU is a legally required document that details how the device should be used, cleaned, and reprocessed.",
    difficulty: "medium",
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 15: Ultrasonic Probes
  // ═══════════════════════════════════════════════════════════════

  {
    id: "cer-ch15-1",
    type: "mcq",
    domain: "Ultrasonic Probes",
    chapter: 15,
    question: "What is the key difference between internal and external ultrasound probes?",
    options: {
      a: "Internal probes are larger; external probes are smaller",
      b: "Internal probes are inserted into body cavities; external probes are passed over body surfaces",
      c: "Internal probes require sterilization; external probes only need cleaning",
      d: "External probes are inserted into the body; internal probes are used externally",
    },
    correct: "b",
    explanation: "Internal probes (such as TEE and endocavitary probes) are inserted into body cavities. External probes are passed over body surfaces. This difference determines the required level of reprocessing.",
    difficulty: "easy",
  },
  {
    id: "cer-ch15-2",
    type: "mcq",
    domain: "Ultrasonic Probes",
    chapter: 15,
    question: "What are the three main sections of a TEE probe?",
    options: {
      a: "Head, body, and tail",
      b: "Distal tip/transducer, handle/control housing, and electrical cord/cable",
      c: "Insertion tube, control body, and universal cord",
      d: "Transducer, light guide, and bending section",
    },
    correct: "b",
    explanation: "A TEE (transesophageal echocardiography) probe has three sections: (A) distal tip/transducer, (B) handle/control housing, and (C) electrical cord/cable. Each section requires specific inspection and handling.",
    difficulty: "medium",
  },
  {
    id: "cer-ch15-3",
    type: "true_false",
    domain: "Ultrasonic Probes",
    chapter: 15,
    question: "Small holes in ultrasound probes can allow fluid invasion into the probe.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. Small holes in probes can allow fluid invasion into internal components. This creates both a patient safety risk (electrical hazard) and an infection control risk (contamination of internal components).",
    difficulty: "medium",
  },
  {
    id: "cer-ch15-4",
    type: "mcq",
    domain: "Ultrasonic Probes",
    chapter: 15,
    question: "What are the three storage conditions required for all ultrasound probes?",
    options: {
      a: "Sterile, dry, and horizontal",
      b: "Environmentally controlled conditions, vented, and storage area with cleanable surfaces",
      c: "Refrigerated, sealed, and labeled",
      d: "Submerged in disinfectant, dark, and at room temperature",
    },
    correct: "b",
    explanation: "All ultrasound probes require: (a) environmentally controlled storage conditions, (b) vented storage area, and (c) storage area with cleanable surfaces. These conditions minimize contamination risk during storage.",
    difficulty: "medium",
  },
  {
    id: "cer-ch15-5",
    type: "true_false",
    domain: "Ultrasonic Probes",
    chapter: 15,
    question: "All AERs can be validated to disinfect ultrasound probes.",
    options: { a: "True", b: "False" },
    correct: "b",
    explanation: "False. Not all AERs can be validated to disinfect ultrasound probes. Only AERs specifically designed and validated for ultrasound probe reprocessing should be used. Probe-compatible AERs are a distinct category.",
    difficulty: "medium",
  },
  {
    id: "cer-ch15-6",
    type: "mcq",
    domain: "Ultrasonic Probes",
    chapter: 15,
    question: "TEE probes are used for which purpose?",
    options: {
      a: "Examining the lower gastrointestinal tract",
      b: "Assessing the heart's function",
      c: "Visualizing the kidneys",
      d: "Examining the nasal passages",
    },
    correct: "b",
    explanation: "TEE (transesophageal echocardiography) probes are used to assess the heart's function. They are inserted into the esophagus to provide close-range ultrasound imaging of the heart structures.",
    difficulty: "easy",
  },
  {
    id: "cer-ch15-7",
    type: "true_false",
    domain: "Ultrasonic Probes",
    chapter: 15,
    question: "Endocavitary probes should be high-level disinfected following the manufacturer's IFU.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. Endocavitary probes contact mucous membranes and are classified as semi-critical devices requiring HLD. The specific method must follow the manufacturer's IFU for that probe model.",
    difficulty: "medium",
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 16: Human Factors
  // ═══════════════════════════════════════════════════════════════

  {
    id: "cer-ch16-1",
    type: "true_false",
    domain: "Human Factors",
    chapter: 16,
    question: "It is important to completely submerge an endoscope during leak testing because some leaks may not be detected if only partially submerged.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. Complete submersion during leak testing ensures that all surfaces and channels are pressurized and any air leaks — even small ones in less obvious locations — can be detected as rising bubbles.",
    difficulty: "medium",
  },
  {
    id: "cer-ch16-2",
    type: "true_false",
    domain: "Human Factors",
    chapter: 16,
    question: "Moisture can create an environment where microorganisms can grow inside a stored endoscope.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. Moisture creates a warm, nutrient-rich environment inside endoscope channels that supports microbial growth. This is why thorough drying — including alcohol flushing — is mandatory before storage.",
    difficulty: "easy",
  },
  {
    id: "cer-ch16-3",
    type: "mcq",
    domain: "Human Factors",
    chapter: 16,
    question: "Which of the following is an example of a personal circumstance that can negatively impact endoscope reprocessing outcomes?",
    options: { a: "Insufficient staffing levels", b: "Poorly designed work area layout", c: "Substance abuse or mental/emotional issues", d: "Lack of access to proper cleaning chemicals" },
    correct: "c",
    explanation: "Personal circumstances that can impact reprocessing outcomes include substance abuse, mental or emotional issues, complacency, stress, illness, and tiredness. Human factors encompass the whole person, not just job-related variables.",
    difficulty: "medium",
  },
  {
    id: "cer-ch16-4",
    type: "mcq",
    domain: "Human Factors",
    chapter: 16,
    question: "Storing endoscopes with valves and water caps in place may cause which problem?",
    options: { a: "Valve corrosion", b: "Impede air circulation and trap moisture", c: "Cross-contamination between scopes", d: "Premature wear on the insertion tube" },
    correct: "b",
    explanation: "Storing endoscopes with valves and water caps in place impedes air circulation and traps moisture inside channels. This creates conditions where microorganisms can grow, defeating the purpose of the reprocessing that was just performed.",
    difficulty: "medium",
  },
  {
    id: "cer-ch16-5",
    type: "mcq",
    domain: "Human Factors",
    chapter: 16,
    question: "Which of the following is a recommended way to stay current on endoscope reprocessing?",
    options: {
      a: "Rely only on initial hire training",
      b: "Read current IFUs, attend formal in-services, and review current standards and guidelines",
      c: "Follow only the most experienced technician's methods",
      d: "Wait for mandatory annual re-training only",
    },
    correct: "b",
    explanation: "Three recommended ways to stay current: (1) reading current Instructions for Use, (2) attending formal in-services, and (3) reviewing current standards and guidelines. Best practices evolve — ongoing education is essential.",
    difficulty: "easy",
  },
  {
    id: "cer-ch16-6",
    type: "true_false",
    domain: "Human Factors",
    chapter: 16,
    question: "Pressure to meet tight turnaround demands increases the risk of shortcuts in endoscope reprocessing.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. Pressure to meet tight turnaround demands is a documented human factor that increases the risk of shortcuts in reprocessing. This is why adequate staffing, inventory, and workflow design are critical patient safety issues.",
    difficulty: "easy",
  },
  {
    id: "cer-ch16-7",
    type: "mcq",
    domain: "Human Factors",
    chapter: 16,
    question: "It is important to use an enzymatic solution during leak testing of an endoscope because escaping air bubbles are easier to see in the solution.",
    options: { a: "True", b: "False", c: "Only for duodenoscopes", d: "Only for bronchoscopes" },
    correct: "b",
    explanation: "False. Enzymatic solution should NOT be used during leak testing. Plain water is used so air bubbles are clearly visible. Enzymatic solutions could obscure bubbles and damage some endoscope components if used inappropriately.",
    difficulty: "hard",
  },
  {
    id: "cer-ch16-8",
    type: "true_false",
    domain: "Human Factors",
    chapter: 16,
    question: "Fluid invasion can occur when a water-resistant cap is not fully on and locked during reprocessing.",
    options: { a: "True", b: "False" },
    correct: "a",
    explanation: "True. Fluid invasion occurs when the water-resistant cap is not fully seated and locked. This allows cleaning solutions or disinfectants to enter internal components, causing serious damage to the endoscope.",
    difficulty: "medium",
  },

];

export const cerQuestionCount = cerQuestions.length;

export const cerQuestionsByChapter = cerQuestions.reduce((acc, q) => {
  acc[q.chapter] = acc[q.chapter] || [];
  acc[q.chapter].push(q);
  return acc;
}, {} as Record<number, CERQuestion[]>);

export const cerQuestionsByDomain = cerQuestions.reduce((acc, q) => {
  acc[q.domain] = acc[q.domain] || [];
  acc[q.domain].push(q);
  return acc;
}, {} as Record<string, CERQuestion[]>);

export const cerMCQCount = cerQuestions.filter(q => q.type === "mcq").length;
export const cerTrueFalseCount = cerQuestions.filter(q => q.type === "true_false").length;

export default cerQuestions;

// Conversion to app-compatible format (array-based options with number index)
export interface AppQuestion {
  id: string;
  question: string;
  options: string[];
  correct_answer: number;
  domain: string;
  difficulty: 'easy' | 'medium' | 'hard';
  explanation: string;
}

const letterToIndex: Record<string, number> = { a: 0, b: 1, c: 2, d: 3 };

export const QUESTIONS: AppQuestion[] = cerQuestions.map((q) => ({
  id: q.id,
  question: q.question,
  options: q.options.c && q.options.d 
    ? [q.options.a, q.options.b, q.options.c, q.options.d]
    : [q.options.a, q.options.b],
  correct_answer: letterToIndex[q.correct],
  domain: q.domain,
  difficulty: q.difficulty,
  explanation: q.explanation,
}));
